"""Initial migration.

Revision ID: 94097ac352a0
Revises: 
Create Date: 2021-06-11 22:19:41.087683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94097ac352a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'test')
    # ### end Alembic commands ###
